//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koval
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int IdDogovora { get; set; }
        public Nullable<int> IdClienta { get; set; }
        public Nullable<int> IdNedviz { get; set; }
        public string nomerDogovora { get; set; }
        public Nullable<System.DateTime> DateSoglas { get; set; }
        public Nullable<System.DateTime> DateRastor { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdSotrudnika { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Nedvizimost Nedvizimost { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
