//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morokva
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Code_zakaza { get; set; }
        public Nullable<int> Code_Sotrudnika { get; set; }
        public Nullable<int> Code_tovara { get; set; }
        public Nullable<System.DateTime> Date_zayavki { get; set; }
        public Nullable<System.DateTime> date_dostavki { get; set; }
        public Nullable<int> Code_Clienta { get; set; }
        public string StatusOrder { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
